language: go
go:
  - 1.2
  - tip
script: make build
install: go get github.com/op/go-logging

notifications:
  email:
    recipients:
      - shell909090@gmail.com
    on_success: never
    on_failure: change